### PR TITLE
Daclassertor

### PR DESCRIPTION
**Pull request by cranberrynut**
This is a request to pull the addition of asserting whether a given AD object grants a role assertion principal all permissions of that role assertion, based on the object DACL.  The `DACLAssertor` class performs the evaluation by first fetching & parsing an object DACL from its SecurityDescriptor - leveraging functionality currently in ADSDDL - and then comparing all `ACE`s of the DACL against `AceAssertion`s in the role assertion.

The comparison is performed by `DACLAssertor.doAssert(AdRoleAssertion)`; any unsatisfied assertions are obtained by then calling `DACLAssertor.getUnsatisfiedAssertions()`.

### CODE REVIEW

**Comment by ilgrosso** [comment]
@cranberrynut you should replace

```

**Comment by ilgrosso** [comment]
@cranberrynut would you also mind to open an issue describing the problem that this PR is solving? Thanks!

**Comment by cranberrynut** [comment]
@ilgrosso I have updated the license headers as per above (as you may have noticed already).
Thanks for changing the build rules!

**Comment by ilgrosso** [comment]
> Thanks for changing the build rules!

np, it was long overdue ;-)

**Pull request merged**
